/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DesignerRouteImport } from './routes/designer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShirtsShirtIdRouteImport } from './routes/shirts.$shirtId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const DesignerRoute = DesignerRouteImport.update({
  id: '/designer',
  path: '/designer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShirtsShirtIdRoute = ShirtsShirtIdRouteImport.update({
  id: '/shirts/$shirtId',
  path: '/shirts/$shirtId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/designer': typeof DesignerRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/shirts/$shirtId': typeof ShirtsShirtIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/designer': typeof DesignerRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/shirts/$shirtId': typeof ShirtsShirtIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/designer': typeof DesignerRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/shirts/$shirtId': typeof ShirtsShirtIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/designer' | '/auth/callback' | '/shirts/$shirtId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/designer' | '/auth/callback' | '/shirts/$shirtId'
  id: '__root__' | '/' | '/designer' | '/auth/callback' | '/shirts/$shirtId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignerRoute: typeof DesignerRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ShirtsShirtIdRoute: typeof ShirtsShirtIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/designer': {
      id: '/designer'
      path: '/designer'
      fullPath: '/designer'
      preLoaderRoute: typeof DesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shirts/$shirtId': {
      id: '/shirts/$shirtId'
      path: '/shirts/$shirtId'
      fullPath: '/shirts/$shirtId'
      preLoaderRoute: typeof ShirtsShirtIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignerRoute: DesignerRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ShirtsShirtIdRoute: ShirtsShirtIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
