/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DesignerRouteImport } from './routes/designer'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShirtsShirtIdRouteImport } from './routes/shirts.$shirtId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ShirtsShirtIdImageDotpngRouteImport } from './routes/shirts.$shirtId_.image[.]png'

const DesignerRoute = DesignerRouteImport.update({
  id: '/designer',
  path: '/designer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShirtsShirtIdRoute = ShirtsShirtIdRouteImport.update({
  id: '/shirts/$shirtId',
  path: '/shirts/$shirtId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ShirtsShirtIdImageDotpngRoute =
  ShirtsShirtIdImageDotpngRouteImport.update({
    id: '/shirts/$shirtId_/image.png',
    path: '/shirts/$shirtId/image.png',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/designer': typeof DesignerRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/shirts/$shirtId': typeof ShirtsShirtIdRoute
  '/shirts/$shirtId/image.png': typeof ShirtsShirtIdImageDotpngRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/designer': typeof DesignerRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/shirts/$shirtId': typeof ShirtsShirtIdRoute
  '/shirts/$shirtId/image.png': typeof ShirtsShirtIdImageDotpngRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/designer': typeof DesignerRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/shirts/$shirtId': typeof ShirtsShirtIdRoute
  '/shirts/$shirtId_/image.png': typeof ShirtsShirtIdImageDotpngRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/designer'
    | '/auth/callback'
    | '/shirts/$shirtId'
    | '/shirts/$shirtId/image.png'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/designer'
    | '/auth/callback'
    | '/shirts/$shirtId'
    | '/shirts/$shirtId/image.png'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/designer'
    | '/auth/callback'
    | '/shirts/$shirtId'
    | '/shirts/$shirtId_/image.png'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DesignerRoute: typeof DesignerRoute
  ShirtsShirtIdRoute: typeof ShirtsShirtIdRoute
  ShirtsShirtIdImageDotpngRoute: typeof ShirtsShirtIdImageDotpngRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/designer': {
      id: '/designer'
      path: '/designer'
      fullPath: '/designer'
      preLoaderRoute: typeof DesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shirts/$shirtId': {
      id: '/shirts/$shirtId'
      path: '/shirts/$shirtId'
      fullPath: '/shirts/$shirtId'
      preLoaderRoute: typeof ShirtsShirtIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/shirts/$shirtId_/image.png': {
      id: '/shirts/$shirtId_/image.png'
      path: '/shirts/$shirtId/image.png'
      fullPath: '/shirts/$shirtId/image.png'
      preLoaderRoute: typeof ShirtsShirtIdImageDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DesignerRoute: DesignerRoute,
  ShirtsShirtIdRoute: ShirtsShirtIdRoute,
  ShirtsShirtIdImageDotpngRoute: ShirtsShirtIdImageDotpngRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
